---
    - name: update all packages
      dnf:
         name: '*'
         state: latest

    - name: set host name
      shell: |
        hostnamectl set-hostname {{ host_name }}
        echo '{{ keycloak_ip }} {{ host_name }}' >> /etc/hosts

    - name: install java
      dnf:
        name: java-1.8.0-openjdk
        state: latest

    - name: install wget
      command: dnf install wget -y

    - name: install keycloak
      shell: |
          mkdir -p {{ keycloak_home }}
          cd /usr/local/keycloak
          wget --no-check-certificate https://downloads.jboss.org/keycloak/{{ keycloak_ver }}/keycloak-{{ keycloak_ver }}.tar.gz
          tar zxvf keycloak-{{ keycloak_ver }}.tar.gz

    - name: create systemd service
      shell: |
         cd {{ keycloak_home }}/docs/contrib/scripts/systemd/
         mkdir /etc/keycloak
         mkdir /var/run/keycloak
         KEYCLOAK_HOME=/usr/local/keycloak/keycloak-3.4.3.Final
         sed -e 's/wildfly/keycloak/g' -e 's/WILDFLY/KEYCLOAK/g'  wildfly.conf > /etc/keycloak/keycloak.conf
         sed -e 's/wildfly/keycloak/g' -e 's/WILDFLY/KEYCLOAK/g' -e "s%KEYCLOAK_HOME=.*%KEYCLOAK_HOME=$KEYCLOAK_HOME%" launch.sh > $KEYCLOAK_HOME/bin/launch.sh
         chmod 755 {{ keycloak_home }}/bin/launch.sh
         sed -e 's/User=.*/User=root/g' -e 's/wildfly/keycloak/g' -e 's/WILDFLY/KEYCLOAK/g' -e 's/Description=.*/Description=Keycloak Identity Provider/g' -e "s%/opt/keycloak/bin%$KEYCLOAK_HOME/bin%" wildfly.service > /etc/systemd/system/keycloak.service
         cd

    - name: create admin user
      shell: |
         {{ keycloak_home }}/bin/add-user-keycloak.sh -r master -u admin -p PASSWORD

    - name: start keycloak service
      systemd:
        name: keycloak
        state: started
        enabled: true

    - name: install python-firewall
      dnf:
        name:
         - python2-firewall
         - firewalld
        state: latest

    - name: open ports
      firewalld: port={{ item }}
                 permanent=True
                 state=enabled
                 immediate=yes
      with_items:
           - 8080/tcp
           - 8443/tcp

    - name: create http service
      shell: |
        echo PASSWORD|kinit admin
        ipa service-add HTTP/{{ host_name }}@{{ ipa_realm }}
        ipa-getkeytab -s {{ ipa_server }} -p HTTP/{{ host_name }}@{{ ipa_realm }} -k /etc/ipa.keytab

    - name: generate java keystore
      shell: |
         cd {{ keycloak_home }}/standalone/configuration
         keytool -genkey -alias {{ domain_name }} -dname "CN={{ host_name }}, OU=Keycloak, O=Red Hat, L=Westford, ST=MA, C=US" -keyalg RSA -keystore keycloak.jks -storepass PASSWORD -keypass PASSWORD -validity 10950

    - name: generate cert request
      shell: |
         cd {{ keycloak_home }}/standalone/configuration
         echo PASSWORD|keytool -certreq -alias {{ domain_name }} -keystore keycloak.jks > keycloak.careq

    - name: sign certificate
      shell: |
        cd {{ keycloak_home }}/standalone/configuration
        ipa cert-request --principal HTTP/{{ host_name }}@{{ ipa_realm }} keycloak.careq

    - name: export certificate
      shell: |
        cd {{ keycloak_home }}/standalone/configuration
        ipa service-show HTTP/{{ host_name }} --out keycloak.cert

    - name: import CA
      shell: |
        cd {{ keycloak_home }}/standalone/configuration
        cp -i /etc/ipa/ca.crt .
        echo yes|keytool -import -keystore keycloak.jks -file ca.crt -alias root -storepass PASSWORD

    - name: import signed cert
      shell: |
        cd {{ keycloak_home }}/standalone/configuration
        echo PASSWORD|keytool -import -keystore keycloak.jks -file keycloak.cert -alias {{ domain_name }} -storepass PASSWORD

    - name: install python libraries
      pip:
        name: lxml

    - name: configure HTTPS
      script: xpath.py

    - name: restart keycloak
      command: systemctl restart keycloak

    - name: install jna, sssd-dbus
      dnf:
        name:
          - jna
          - sssd-dbus
          - https://github.com/keycloak/libunix-dbus-java/releases/download/libunix-dbus-java-0.8.0/libunix-dbus-java-0.8.0-1.fc24.x86_64.rpm
        state: latest

    - name: setup SSSD federation
      shell: |
        cd {{ keycloak_home }}
        bin/federation-sssd-setup.sh
        systemctl restart sssd
        systemctl restart keycloak
