---
- name: fix dns
  shell: |
    echo 'nameserver {{ ipa_host_ip }}' >> /etc/resolv.conf

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install ipa client packages
  yum:
    name:  ipa-client, ipa-admintools
    state: latest

#need to figure out how to make the DNS
- name: add hostname
  shell: |
    hostnamectl set-hostname {{ host_name }} 
    echo '{{ host_ip_address }} {{ host_name }}' >> /etc/hosts 

#should be able to find server through DNS
- name: make IPA client
  command: >
    ipa-client-install -U
    --fixed-primary
    --principal admin
    --password PASSWORD
    --force-join
