---
- name: fix dns
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: nameserver {{ ipa_host_ip }}

- name: add 1.1.1.1 to resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: nameserver 1.1.1.1

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install ipa client packages
  yum:
    name:
      - ipa-client
      - ipa-admintools
    state: latest

- name: add hostname
  shell: |
    hostnamectl set-hostname {{ host_name }}
    echo '{{ host_ip }} {{ host_name }}' >> /etc/hosts

#should be able to find server through DNS
- name: make IPA client
  command: >
    ipa-client-install -U
    --fixed-primary
    --principal admin
    --password PASSWORD
    --force-join
